short_to_long_function_def = true
always_for_in = true
whitespace_ops_in_indices = true
pipe_to_function_call = true
import_to_using = true
always_use_return = true
whitespace_in_kwargs = false
remove_extra_newlines = true
annotate_untyped_fields_with_any = false
conditional_to_if = false
