project:
  title: "Manifolds.jl Tutorials"
  output-dir: ../docs/src/tutorials
  render:
    - "*.qmd"

crossref:
  fig-prefix: Figure
  tbl-prefix: Table
fig-format: png

execute:
  freeze: auto
  eval: true
  echo: true
  output: true

format:
  commonmark:
    variant: -raw_html+tex_math_dollars+pipe_tables+footnotes
    wrap: preserve

engines: ['julia']
